### PR TITLE
Fix maven + enhancements...

### PR DESCRIPTION
**Pull request by sgdc3**

### CODE REVIEW

**Comment by sgdc3** [comment]
Are you ok about the license change? :) @NoChanceSD

**Comment by sgdc3** [comment]
Also fixed 1.7 compatibility

**Comment by sgdc3** [comment]
Only one issue: huge jar due to shaded libs (gson and guava required for 1.7 compatibility)

**Comment by ChanceSD** [comment]
I think the license has to remain GPLv2 as in the "original" http://dev.bukkit.org/bukkit-plugins/ancient-gates-reloaded . Not sure about that though.
Also did Guava really break on 1.8? I remember testing the plugin with 1.7.10 and it worked fine.

**Comment by sgdc3** [comment]
It's broken with kcauldron ;) I'll keep gplv2

**Comment by sgdc3** [comment]
@NoChanceSD Done ;)

**Comment by ChanceSD** [comment]
Shading guava as well doesn't seem a very good idea, i don't know how big is the final jar but if it's huge maybe just don't support kcauldron...

**Comment by sgdc3** [comment]
1,6Mb c.a.

**Comment by sgdc3** [comment]
Another solution is to build the project under an old version of guava.

**Comment by ChanceSD** [comment]
I will take a better look at this in a few days. Btw, why remove metrics custom graphs, i think that could stay the same.

**Comment by sgdc3** [comment]
Ah, i missed them, i'll readd them asap ;)

**Comment by ChanceSD** [comment]
Are you going to re-add metrics? Otherwise, i also can do it.

**Comment by sgdc3** [comment]
Lol sorry I forgot about it! I'll try to finish it today, but if you prefer you can do it by yourself (in the main class use the API methods to add a new custom graph) :)
Docs:
- https://github.com/Hidendra/Plugin-Metrics/wiki/Usage
- https://github.com/Hidendra/Plugin-Metrics/wiki/Custom-Graphs

**Comment by ChanceSD** [comment]
lol I know how to add it but it's not necessary, i just wanted you to undelete MetricsStarter class.

**Comment by sgdc3** [comment]
Ah ok, sorry, after a week i can't remember how you start metrics ;)

**Comment by sgdc3** [comment]
Done @NoChanceSD

**Comment by ChanceSD** [comment]
Ok thanks!

**Pull request merged**
